add html_prototype
jimmyhollywood2/python-epam pull request #4
Opened 2019-08-19 19:45 UTC by jimmyhollywood

2019-08-20 09:48 UTC, inauros requested changes
Please fix the following issues:
1. Edit button doesn't work on the Employees and Departments pages
2. Delete button doesn't work on the Employees and Departments pages
3. ADD EMPLOYEE form: please change type of the Department field (it should be dropdown with existing departments)
4. Search by Date of Birth doesn't work

2019-08-26 09:24 UTC, inauros commented on .gitignore
> +.vscode/
Please add __pycache__ to gitignore

2019-08-26 09:26 UTC, inauros commented on officemanager/officemanager/settings.py
> +        'ENGINE': 'django.db.backends.sqlite3',
In accordance with requirements, you should use MySQL instead of SQLite

2019-08-26 09:29 UTC, inauros commented on officemanager/setup.py
> +    ],
Install_requires is missing. Please add install_requires with all required dependencies (django, DRF, etc).

2019-08-26 09:31 UTC, inauros commented
Please use packages instead of modules, as described in Step 8.

2019-08-26 09:32 UTC, inauros commented
Please remover __pycache__ from the project

2019-08-26 09:32 UTC, inauros requested changes
Please fix the project structure in accordance with the latest comments

2019-08-26 18:40 UTC, jimmyhollywood commented
DATABASE upd:
`DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'newdatabasename',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306'
    }
}`

2019-08-27 09:30 UTC, inauros approved these changes
Approving these changes.

2019-08-28 18:36 UTC, merged